name: Node.js CI

on:
  push:
    branches:
      - main
      - next
jobs:
  build-and-publish:
    name: build-and-publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Biome
        uses: biomejs/setup-biome@v2
        with:
          version: latest
      - name: Run Biome
        run: biome ci .
      - name: 'Setup node'
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://registry.npmjs.org

      - name: install deps, tests and build
        run: |
          npm ci --no-audit
          npm run test
          npm run build --if-present
        env:
          CI: true

      - name: publish to npm
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
